style: extend the linting rules and lint the project
Signed-off-by: Martin Dünkelmann <nc-duenkekl3@netcologne.de>

diff --git a/.github/workflows/ci_development.yml b/.github/workflows/ci_development.yml
--- a/.github/workflows/ci_development.yml
+++ b/.github/workflows/ci_development.yml
@@ -1,56 +1,56 @@
 name: CI Development
 on:
-  push:
-    branches:
-      - master
-  pull_request:
-    branches:
-      - master
+    push:
+        branches:
+            - master
+    pull_request:
+        branches:
+            - master
 jobs:
-  ci_dev:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-      - name: Setup node env
-        uses: actions/setup-node@v3.1.1
-        with:
-          cache: 'npm'
-          check-latest: true
-          node-version: 16
-      - name: Install dependencies
-        run: npm install
-      - name: Commit dependency changes
-        if: ${{ !github.event.issue.pull_request && github.event.action != 'opened' && github.event.action != 'synchronize' }}
-        run: |
-          echo "START: Reasons why it fails if it fails"
-          echo "github.event.issue.pull_request: ${{ github.event.issue.pull_request }}"
-          echo "github.event.action: ${{ github.event.action }}"
-          echo "Reasons why it fails if it fails :END"
-          git config --global user.name 'Github Actions'
-          git config --global user.email 'github.actions@users.noreply.github.com'
-          git add . || true
-          git commit -am "build: update dependencies" || true
-          git push || true
-      - name: Run linter
-        run: npm run lint
-      - name: Run static website generator
-        run: npm run generate
-      - name: Deploy to github branch
-        if: ${{ !github.event.issue.pull_request && github.event.action != 'opened' && github.event.action != 'synchronize' }}
-        uses: JamesIves/github-pages-deploy-action@releases/v3
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH: gh-pages
-          FOLDER: dist
-  auto-merge:
-    needs: ci_dev
-    permissions:
-      contents: write
-      pull-requests: write
-    runs-on: ubuntu-latest
-    steps:
-      - uses: fastify/github-action-merge-dependabot@v3.1
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          target: patch
+    ci_dev:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout repo
+              uses: actions/checkout@v3
+            - name: Setup node env
+              uses: actions/setup-node@v3.1.1
+              with:
+                  cache: 'npm'
+                  check-latest: true
+                  node-version: 16
+            - name: Install dependencies
+              run: npm install
+            - name: Commit dependency changes
+              if: ${{ !github.event.issue.pull_request && github.event.action != 'opened' && github.event.action != 'synchronize' }}
+              run: |
+                  echo "START: Reasons why it fails if it fails"
+                  echo "github.event.issue.pull_request: ${{ github.event.issue.pull_request }}"
+                  echo "github.event.action: ${{ github.event.action }}"
+                  echo "Reasons why it fails if it fails :END"
+                  git config --global user.name 'Github Actions'
+                  git config --global user.email 'github.actions@users.noreply.github.com'
+                  git add . || true
+                  git commit -am "build: update dependencies" || true
+                  git push || true
+            - name: Run linter
+              run: npm run lint
+            - name: Run static website generator
+              run: npm run generate
+            - name: Deploy to github branch
+              if: ${{ !github.event.issue.pull_request && github.event.action != 'opened' && github.event.action != 'synchronize' }}
+              uses: JamesIves/github-pages-deploy-action@releases/v3
+              with:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  BRANCH: gh-pages
+                  FOLDER: dist
+    auto-merge:
+        needs: ci_dev
+        permissions:
+            contents: write
+            pull-requests: write
+        runs-on: ubuntu-latest
+        steps:
+            - uses: fastify/github-action-merge-dependabot@v3.1
+              with:
+                  github-token: ${{ secrets.GITHUB_TOKEN }}
+                  target: patch
